apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
      disableNameSuffixHash: true

configMapGenerator:
  - name: otel-collector-config
    namespace: aks
    options:
      labels:
        app: otel-collector
    files:
      - otel-collector-config.yaml=data/otel-collector-config.yaml

resources:
  - python-configmap.yaml
  - python-service.yaml
  - python-deployment.yaml
